Objective
Separate features and target variable.
Split the dataset into training and testing sets.
Scale numerical features using StandardScaler and MinMaxScaler.
Save the scaler for deployment.

Import Required Libraries

In [1]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, MinMaxScaler

import joblib

Load the Dataset

In [2]:
df = pd.read_csv("../data/crop_yield_selected_features.csv")

df.head()

   Production       Area  Season  Fertilizer  Fertilizer_per_Area   Yield
0   10.945688  11.209317       4   15.764969             1.291224  0.7960
1    8.452335   8.800566       1   13.356082             1.362787  0.7100
2    3.135494   6.680855       1   11.235277             1.462764  0.2380
3   18.434232   9.886189       4   14.441803             1.326617  5.0725
4    6.678342   7.461640       1   12.016736             1.420143  0.4210

Check Dataset

In [3]:
df.shape
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 19689 entries, 0 to 19688
Data columns (total 6 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Production           19689 non-null  float64
 1   Area                 19689 non-null  float64
 2   Season               19689 non-null  int64
 3   Fertilizer           19689 non-null  float64
 4   Fertilizer_per_Area  19689 non-null  float64
 5   Yield                19689 non-null  float64
dtypes: float64(5), int64(1)
memory usage: 923.1 KB

Separate Features and Target

In [5]:
X = df.drop("Yield", axis=1)

y = df["Yield"]

Display Shapes

In [6]:
print("Features Shape :", X.shape)

print("Target Shape :", y.shape)

Features Shape : (19689, 5)
Target Shape : (19689,)

Train-Test Split

In [7]:
#Split the dataset into 80% training and 20% testing.

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42
)

Check Shapes

In [8]:

print("Training Features :", X_train.shape)

print("Testing Features :", X_test.shape)

print("Training Target :", y_train.shape)

print("Testing Target :", y_test.shape)

Training Features : (15751, 5)
Testing Features : (3938, 5)
Training Target : (15751,)
Testing Target : (3938,)

Standard Scaling

In [9]:
#Create the scaler.

scaler = StandardScaler()

In [10]:
#Fit only on training data.

X_train_scaled = scaler.fit_transform(X_train)

In [11]:
#Transform testing data.

X_test_scaled = scaler.transform(X_test)

In [12]:
# Convert Back to DataFrame 
X_train_scaled = pd.DataFrame(
    X_train_scaled,
    columns=X_train.columns
)

X_test_scaled = pd.DataFrame(
    X_test_scaled,
    columns=X_test.columns
)

In [13]:
 #View Scaled Data
X_train_scaled.head()

   Production      Area    Season  Fertilizer  Fertilizer_per_Area
0   -0.724400 -1.076235 -0.850832   -1.001347             0.686474
1   -1.204401 -1.599963 -0.850832   -1.606019             1.256777
2   -1.449328 -1.264640  1.601401   -1.344966             0.599452
3    0.204588  0.300624 -0.033421    0.342320            -0.335839
4    0.999452  1.404691 -0.850832    1.289464            -0.851888

In [14]:
#Verify Scaling
print(X_train_scaled.describe().round(2))

       Production      Area    Season  Fertilizer  Fertilizer_per_Area
count    15751.00  15751.00  15751.00    15751.00             15751.00
mean        -0.00     -0.00     -0.00        0.00                 0.00
std          1.00      1.00      1.00        1.00                 1.00
min         -2.59     -2.64     -1.67       -2.63                -1.03
25%         -0.63     -0.62     -0.85       -0.62                -0.55
50%          0.04      0.03     -0.03        0.02                -0.26
75%          0.67      0.73      0.78        0.73                 0.15
max          2.63      2.75      2.42        2.75                 5.73

Min-Max Scaling

In [16]:
minmax = MinMaxScaler()

X_train_minmax = minmax.fit_transform(X_train)

X_test_minmax = minmax.transform(X_test)

#Convert to DataFrame.

X_train_minmax = pd.DataFrame(
    X_train_minmax,
    columns=X_train.columns
)

X_test_minmax = pd.DataFrame(
    X_test_minmax,
    columns=X_test.columns
)

Compare StandardScaler and MinMaxScaler

In [17]:
print("Standard Scaled Data")

print(X_train_scaled.head())

print("MinMax Scaled Data")

print(X_train_minmax.head())

Standard Scaled Data
   Production      Area    Season  Fertilizer  Fertilizer_per_Area
0   -0.724400 -1.076235 -0.850832   -1.001347             0.686474
1   -1.204401 -1.599963 -0.850832   -1.606019             1.256777
2   -1.449328 -1.264640  1.601401   -1.344966             0.599452
3    0.204588  0.300624 -0.033421    0.342320            -0.335839
4    0.999452  1.404691 -0.850832    1.289464            -0.851888
MinMax Scaled Data
   Production      Area  Season  Fertilizer  Fertilizer_per_Area
0    0.357723  0.289938     0.2    0.302946             0.254245
1    0.265752  0.192807     0.2    0.190476             0.338551
2    0.218822  0.254996     0.8    0.239032             0.241381
3    0.535724  0.545289     0.4    0.552871             0.103120
4    0.688025  0.750049     0.2    0.729042             0.026834

Save the StandardScaler

In [18]:
joblib.dump(scaler, "standard_scaler.pkl")

print("StandardScaler saved successfully.")

StandardScaler saved successfully.

Save the MinMaxScaler

In [19]:
joblib.dump(minmax, "minmax_scaler.pkl")

print("MinMaxScaler saved successfully.")

MinMaxScaler saved successfully.

Save Training and Testing Data

In [21]:
from pathlib import Path

# Current notebook location
print(Path.cwd())

# If notebook is in notebooks/
project_root = Path.cwd().parent

data_folder = project_root / "data"
data_folder.mkdir(exist_ok=True)  # Creates the folder if it doesn't exist


X_train_scaled.to_csv(data_folder / "X_train_scaled.csv", index=False)

X_test_scaled.to_csv(data_folder / "X_test_scaled.csv", index=False)

y_train.to_csv(data_folder / "y_train.csv", index=False)

y_test.to_csv(data_folder / "y_test.csv", index=False)

c:\Users\Ranjana\Crop_Yield_Prediction\notebooks

In [22]:
#Summary

print("Train-Test Split Completed")
print("Training Samples :", len(X_train))
print("Testing Samples :", len(X_test))
print("Number of Features :", X_train.shape[1])

Train-Test Split Completed
Training Samples : 15751
Testing Samples : 3938
Number of Features : 5